tinker-userspace: malloc.h File Reference
malloc.h File Reference
Functions
int init_malloc (char *mem_block_algo)
void * tmalloc (int size)
void tfree (void *ptr)
Function Documentation
init_malloc()
int init_malloc (char * algo_name)
Intializes global variables and block finding algorithm
Note Currently only supports "first_fit_block_algo", if function is passed invalid function name returns with -1
Definition at line 206 of file malloc.c.
Referenced by main().
tfree()
void tfree (void * ptr)
Frees given block Note: fails silently
Parameters
[in] ptr Pointer to the block that needs to be freed
Definition at line 258 of file malloc.c.
Referenced by main().
tmalloc()
void* tmalloc (int size)
Tries to allocate memory of given size
returns pointer to memory if successful else returns NULL
Definition at line 230 of file malloc.c.
Referenced by main().