tinker-userspace: malloc.c File Reference
malloc.c File Reference
#include <errno.h>
#include <stdbool.h>
#include <stdio.h>
#include <string.h>
#include <sys/mman.h>
#include <sys/types.h>
#include <unistd.h>
#include "llist.h"
#include "malloc.h"
Classes
struct block_hdr
Macros
#define _DEFAULT_SOURCE
#define INCREMENT 4096
Typedefs
typedef struct block_hdr block_hdr
typedef block_hdr * Block_hdr
Functions
LL_HEAD (head)
void * first_fit_block_algo (int size)
void * failsafe_check_tail_block (int size)
void merge_adjacent_blocks_algo (void *ptr)
int request_memory ()
void * malloc_mem (void *block, int size)
int init_malloc (char *algo_name)
void * tmalloc (int size)
void tfree (void *ptr)
Variables
void *(* mem_block_algo)(int)
void *(* failsafe_block_algo)(int)
void(* defrag_block_algo)(void *)
int ret
Macro Definition Documentation
_DEFAULT_SOURCE
#define _DEFAULT_SOURCE
Definition at line 1 of file malloc.c.
INCREMENT
#define INCREMENT 4096
Definition at line 14 of file malloc.c.
Typedef Documentation
block_hdr
typedef struct block_hdr block_hdr
The block_hdr struct represents the structure of the block header.
A block header stores additional information about the newly allocated block. Part of this information helps to keep the track of the block size so that free and realloc can work properly.
See also
https://stackoverflow.com/questions/7717296/malloc-header-contents
Block_hdr
typedef block_hdr* Block_hdr
Definition at line 42 of file malloc.c.
Function Documentation
failsafe_check_tail_block()
void* failsafe_check_tail_block (int size)
Checks if last block satisfied memory requirement
Note: Ideally should be called after requesting more memory as newly created arena will be added to tail of blocks Returns header of the tail block if the tail block has space and is unallocated, else returns NULL
Definition at line 92 of file malloc.c.
first_fit_block_algo()
void* first_fit_block_algo (int size)
Function first_fit_block_algo returns unallocated block of the size.
Traverse all blocks and return first unallocated block that satisfies size requirement. It takes care to allocate extra space needed for the block header. Returns NULL on failing
Parameters
[in] size The amount of size in bytes that is needed (Excluding the size of the header)
Definition at line 61 of file malloc.c.
init_malloc()
int init_malloc (char * algo_name)
Intializes global variables and block finding algorithm
Note Currently only supports "first_fit_block_algo", if function is passed invalid function name returns with -1
Definition at line 206 of file malloc.c.
Referenced by main().
LL_HEAD()
LL_HEAD (head)
malloc_mem()
void* malloc_mem (void * block, int size)
Allocate memory from given block. Mark block as allocated and break it into a new unallocated block
Definition at line 172 of file malloc.c.
merge_adjacent_blocks_algo()
void merge_adjacent_blocks_algo (void * ptr)
Merge adjacent unallocated blocks
Merges all the adjacent unused "freed" memory. This way larger blocks of memory are now available.
Definition at line 116 of file malloc.c.
request_memory()
int request_memory ()
Request more heap memory by incrementing program break
Program break represents the first location after the end of the uninitialized data segment. sbrk is a system call which increases/decreases the amount of allocated memory
See also
https://en.wikipedia.org/wiki/Sbrk
{https://stackoverflow.com/questions/6988487/what-does-the-brk-system-call-do}
Definition at line 148 of file malloc.c.
tfree()
void tfree (void * ptr)
Frees given block Note: fails silently
Parameters
[in] ptr Pointer to the block that needs to be freed
Definition at line 258 of file malloc.c.
Referenced by main().
tmalloc()
void* tmalloc (int size)
Tries to allocate memory of given size
returns pointer to memory if successful else returns NULL
Definition at line 230 of file malloc.c.
Referenced by main().
Variable Documentation
defrag_block_algo
void(* defrag_block_algo) (void *)
Definition at line 21 of file malloc.c.
failsafe_block_algo
void*(* failsafe_block_algo) (int)
Definition at line 19 of file malloc.c.
mem_block_algo
void*(* mem_block_algo) (int)
Definition at line 18 of file malloc.c.
ret
int ret
Definition at line 22 of file malloc.c.