.TH "llhead" 3 "Wed Oct 30 2019" "tinker-userspace" \" -*- nroff -*-
.ad l
.nh
.SH NAME
llhead
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <llist\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBllhead\fP * \fBprev\fP"
.br
.ti -1c
.RI "struct \fBllhead\fP * \fBnext\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 17 of file llist\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "struct \fBllhead\fP* llhead::next"

.PP
Definition at line 19 of file llist\&.h\&.
.SS "struct \fBllhead\fP* llhead::prev"

.PP
Definition at line 18 of file llist\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for tinker-userspace from the source code\&.
